server:
  node: ${LOCAL_SERVER_NODE:0}
  shutdown: graceful

spring:
  jpa:
    hibernate:
      ddl-auto: ${LOCAL_DDL_AUTO:update}
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/wooco-local-database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: wooco-local-user
    password: wooco-local-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:
      repositories:
        enabled: false

app:
  jwt:
    signing-key: hong-jun2-eric-erica-jamie-hong-jun2-eric-erica-jamie
    expiration:
      access-token: 987654321
      refresh-token: 987654321

logging.level.root: info
