server:
  node: ${LOCAL_SERVER_NODE:0}
  shutdown: graceful

spring:
  cookie:
    path: /
    max-age: 9876543210
    same-site: Lax
    domain: localhost
    secure: false
    http-only: true

  jpa:
    hibernate:
      ddl-auto: ${LOCAL_DDL_AUTO:update}
    open-in-view: false

  datasource:
    url: jdbc:mysql://localhost:3306/wooco-local-database?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: wooco-local-user
    password: wooco-local-password
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:
      repositories:
        enabled: false

  security:
    user:
      name: local-actuator
      password: local-actuator

app:
  jwt:
    signing-key: hong-jun2-eric-erica-jamie-hong-jun2-eric-erica-jamie
    expiration:
      access-token: 987654321
      refresh-token: 987654321

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    url: /api-docs
    disable-swagger-default-url: true

logging.level.root: info
